/* eslint-disable */
/**
 * Generated API stub.
 *
 * THIS FILE IS A STUB for development outside of `npx convex dev`.
 * When deployed with Convex, this file is auto-generated by the Convex CLI.
 *
 * Using `anyApi` as recommended by Convex docs for projects not using codegen.
 * See: https://docs.convex.dev/api/modules/server#anyapi
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
