/* eslint-disable */
/**
 * Generated data model stub.
 *
 * THIS FILE IS A STUB for development outside of `npx convex dev`.
 * When deployed with Convex, this file is auto-generated by the Convex CLI.
 */
import type { GenericDataModel, GenericId } from "convex/values";

// Table name union
export type TableNames =
  | "canvasConnections"
  | "materials"
  | "sessions"
  | "messages";

// Id type parameterized by table name
export type Id<T extends TableNames> = GenericId<T>;

// DataModel type (used by server function builders)
export type DataModel = GenericDataModel;
